import { LICENSE_OPTIONS } from '@/config';
import { t, type Locale } from '@/i18n';
import type { EditorLabels } from '@/lib/views/editor';

/** 许可证下拉选项（客户端渲染表单，需服务端预翻译） */
export function buildLicenseOptions(locale: Locale): { value: string; label: string }[] {
  return LICENSE_OPTIONS.map((option) => ({
    value: option.value,
    label: option.labelKey ? t(locale, option.labelKey) : (option.label ?? option.value),
  }));
}

/** 编辑器页面的标签对象（服务端构建后序列化给客户端） */
export function buildEditorLabels(locale: Locale): EditorLabels {
  return {
    demoBanner: t(locale, 'editor.demoBanner'),
    repo: t(locale, 'editor.repo'),
    slug: t(locale, 'editor.slug'),
    typeLabel: t(locale, 'editor.typeLabel'),
    titleLabel: t(locale, 'editor.titleLabel'),
    titlePh: t(locale, 'editor.titlePh'),
    videos: t(locale, 'editor.videos'),
    add: t(locale, 'editor.add'),
    remove: t(locale, 'editor.remove'),
    limitHint: t(locale, 'editor.limitHint'),
    params: t(locale, 'editor.params'),
    cover: t(locale, 'editor.cover'),
    coverChoose: t(locale, 'editor.coverChoose'),
    coverReplace: t(locale, 'editor.coverReplace'),
    coverRemove: t(locale, 'editor.coverRemove'),
    body: t(locale, 'editor.body'),
    write: t(locale, 'editor.write'),
    preview: t(locale, 'editor.preview'),
    tagsLabel: t(locale, 'editor.tagsLabel'),
    tagsPh: t(locale, 'editor.tagsPh'),
    files: t(locale, 'editor.files'),
    filesHint: t(locale, 'editor.filesHint'),
    fileTooLarge: t(locale, 'editor.fileTooLarge'),
    scheme: t(locale, 'editor.scheme'),
    schemeRaw: t(locale, 'editor.schemeRaw'),
    schemeFormat: t(locale, 'editor.schemeFormat'),
    schemeZip: t(locale, 'editor.schemeZip'),
    schemeEncrypt: t(locale, 'editor.schemeEncrypt'),
    attachments: t(locale, 'editor.attachments'),
    attachmentChoose: t(locale, 'editor.attachmentChoose'),
    existing: t(locale, 'editor.existing'),
    license: t(locale, 'label.license'),
    authRequired: t(locale, 'editor.authRequired'),
    platform: t(locale, 'editor.platform'),
    tokenPh: t(locale, 'editor.tokenPh'),
    tokenSave: t(locale, 'editor.tokenSave'),
    tokenBad: t(locale, 'editor.tokenBad'),
    submit: t(locale, 'editor.submit'),
    save: t(locale, 'editor.save'),
    publishing: t(locale, 'editor.publishing'),
    stepIssue: t(locale, 'editor.stepIssue'),
    stepFiles: t(locale, 'editor.stepFiles'),
    stepReadme: t(locale, 'editor.stepReadme'),
    stepRelease: t(locale, 'editor.stepRelease'),
    stepAssets: t(locale, 'editor.stepAssets'),
    stepIndex: t(locale, 'editor.stepIndex'),
    stepCover: t(locale, 'editor.stepCover'),
    stepSkipped: t(locale, 'editor.stepSkipped'),
    doneNew: t(locale, 'editor.doneNew'),
    doneEdit: t(locale, 'editor.doneEdit'),
    gotoCollection: t(locale, 'editor.gotoCollection'),
    gotoSubmission: t(locale, 'editor.gotoSubmission'),
    errTitle: t(locale, 'editor.errTitle'),
    errSlug: t(locale, 'editor.errSlug'),
    errRepo: t(locale, 'editor.errRepo'),
    errPassword: t(locale, 'editor.errPassword'),
    errCoverType: t(locale, 'editor.errCoverType'),
    errLoad: t(locale, 'editor.errLoad'),
    typeProject: t(locale, 'type.project'),
    typeArticle: t(locale, 'type.article'),
    paramsWith: t(locale, 'params.with'),
    paramsTuned: t(locale, 'params.tuned'),
    paramsNone: t(locale, 'params.none'),
    tracks: t(locale, 'label.tracks'),
    engines: t(locale, 'label.engines'),
    voicebanks: t(locale, 'label.voicebanks'),
    songLanguages: t(locale, 'label.songLanguages'),
  };
}
